### ISSUE TITLE
Regarding evaluation on Winobias dataset

### ISSUE THREAD

**Issue by VSSILPA** [hangligit/InterpretDiffusion#1]
Thank you for releasing the code.

When I try to evaluate on the Winobias dataset, I get the following error :

"ValueError: You have to specify either input_ids"

I am assuming that this error occurs since the clip_attributes are None. Could you please mention the arguments that you used to evaluate winobias during the testing?

**Comment by hangligit** [comment]
Thank you for your question! Please see the updated README.
